### ISSUE TITLE
wrong no-mutation behavior

### ISSUE THREAD

**Issue by budarin** [jhusain/eslint-plugin-immutable#9]
```
app.use(function * () {
    this.type = 'text/html';
    this.body = fs.createReadStream(path.join(__dirname, 'index.html'));
});
```

this.type - error - no-mutations

**Comment by ljharb** [comment]
@budarin indeed those are both mutations and should not be allowed by this plugin.

**Comment by budarin** [comment]
it's not object mutation - it's koa server lifecircle
there is no methods to do this with another way (http://koajs.com/)

**Comment by ljharb** [comment]
@budarin yes, which means that koa is incompatible with immutability. Mutating `this` is absolutely object mutation.

**Comment by budarin** [comment]
Yes, you are right - I should put this file into eslintignore
Thanks

**Comment by veeracs** [comment]
How do I avoid `no-mutation` error when adding props to a React component like below?

```
Header.propTypes = {
 layout: PropTypes.object,
 actions: PropTypes.object
};
```

**Comment by ljharb** [comment]
@veeracs i don't think you can without the `static` properties proposal enabled

**Comment by joshburgess** [comment]
I ran into this when setting default configuration values for Axios. It seems to me that there is no real way around dealing with library APIs which require object mutation to set their configuration. Is it assumed we just abstract all such code out into separate files and then add those files to our .eslintignore config? 

I like the idea of this plugin and think it's a good idea to help enforce best practices, particularly with team members who might need a bit of coaching to write in a more functional/immutable way, but it's not practical to disallow common libraries that need to be used to get things done due to them not offering a compatible API.
